"""应用层只依赖此协议，SQLAlchemy 等基础设施不反向泄漏到执行逻辑。"""

from typing import Any, Protocol

from agentflow.domain.execution.task import Task


class ExecutionStore(Protocol):
    def claim(self, lease_seconds: float) -> Task | None: ...
    def heartbeat(self, task: Task, lease_seconds: float) -> bool: ...
    def complete(self, task: Task, output: Any) -> bool: ...
    def fail(self, task: Task, error: Exception) -> bool: ...
